services:
  cache-common:
    sysctls:
        - net.ipv4.tcp_rmem=16384 4194304 536870912
        - net.ipv4.tcp_wmem=16384 4194304 536870912
        - net.core.somaxconn=65535
        - net.ipv4.tcp_tw_reuse=1
        - net.ipv4.ip_local_port_range=1024 65535
        - net.ipv4.tcp_fin_timeout=1
    ulimits:
      nofile:
        soft: "1048576"
        hard: "1048576"
    environment:
      - SERVER_PORT=9001
      - METRICS_PORT=8080
      - METRICS_HOST=0.0.0.0
      - NUM_SHARDS=128
      - TRASH_EMPTY_FREQUENCY=10000
      - SOCK_BUF_SIZE=4194304 # request 4 mb socket buffer, depends on system tcp_rmem and tcp_wmem settings
    ports:
      - "9001:9001"
      - "8080:8080"

  tests-common:
    build:
      context: tests
      dockerfile: Dockerfile
    sysctls:
        - net.ipv4.tcp_rmem=16384 4194304 536870912
        - net.ipv4.tcp_wmem=16384 4194304 536870912
    ulimits:
      nofile:
        soft: "1048576"
        hard: "1048576"
    environment:
      - CACHE_PORT=9001
      - CACHE_TYPE=custom
      - TEST_DATA_FOLDER=./data