services:
  cache:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - SERVER_PORT=9001
      - METRICS_PORT=8080
    ports:
      - "9001:9001"
      - "8080:8080"
    profiles:
      - main

  tests:
    build:
      context: tests
      dockerfile: Dockerfile
    environment:
      - CACHE_HOST=cache
      - CACHE_PORT=9001
      - TEST_DELAY_SEC=1
      - TEST_ITERATIONS=1000000
    profiles:
      - tests