services:
  cache:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - empty=empty
    ports:
      - "9001:9001"
      - "8080:8080"

  tests:
    build:
      context: tests
      dockerfile: Dockerfile
    environment:
      - CACHE_HOST=cache
      - CACHE_PORT=9001
      - TEST_DELAY=1
      - TEST_ITERATIONS=1000
    depends_on:
      - cache