services:
  cache:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - BUILD_TYPE=Release
    environment:
      - SERVER_PORT=9001
      - METRICS_PORT=8080
      - METRICS_HOST=0.0.0.0
    ports:
      - "9001:9001"
      - "8080:8080"
    profiles:
      - main

  cache-valgrind:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - BUILD_TYPE=Debug
    entrypoint: ["valgrind", "--leak-check=full", "--show-leak-kinds=all", "--track-origins=yes", "--verbose", "/app/poor-man-s-cache"]
    environment:
      - SERVER_PORT=9001
      - METRICS_PORT=8080
      - METRICS_HOST=0.0.0.0
    ports:
      - "9001:9001"
      - "8080:8080"
    profiles:
      - valgrind

  cache-callgrind:
    build:
      context: .
      dockerfile: Dockerfile.callgrindd
      args:
        - BUILD_TYPE=Release
    environment:
      - SERVER_PORT=9001
      - METRICS_PORT=8080
      - METRICS_HOST=0.0.0.0
    ports:
      - "9001:9001"
      - "8080:8080"
    profiles:
      - callgrind

  tests:
    build:
      context: tests
      dockerfile: Dockerfile
    environment:
      - CACHE_HOST=cache
      - CACHE_PORT=9001
      - CACHE_TYPE=custom
      - TEST_DELAY_SEC=1
      - TEST_ITERATIONS=1000000
    profiles:
      - tests

  tests-valgrind:
    build:
      context: tests
      dockerfile: Dockerfile
    environment:
      - CACHE_HOST=cache-valgrind
      - CACHE_PORT=9001
      - CACHE_TYPE=custom
      - TEST_DELAY_SEC=1
      - TEST_ITERATIONS=10000
    profiles:
      - tests-valgrind

  tests-callgrind:
    build:
      context: tests
      dockerfile: Dockerfile
    environment:
      - CACHE_HOST=cache-callgrind
      - CACHE_PORT=9001
      - CACHE_TYPE=custom
      - TEST_DELAY_SEC=1
      - TEST_ITERATIONS=10000
    profiles:
      - tests-callgrind

  redis:
    image: redis:latest
    container_name: redis-server
    ports:
      - "6379:6379"
    command: ["redis-server"]
    profiles:
      - redis

  tests_redis:
    build:
      context: tests
      dockerfile: Dockerfile
    environment:
      - CACHE_HOST=redis
      - CACHE_PORT=6379
      - CACHE_TYPE=redis
      - TEST_DELAY_SEC=2
      - TEST_ITERATIONS=10000000
    profiles:
      - redis
    depends_on:
      - redis

  redis-exporter:
    image: oliver006/redis_exporter:alpine
    ports:
      - 9121:9121
    command:
      - '--redis.addr=redis://redis:6379'
    profiles:
      - redis
    depends_on:
      - redis
  
  redis-insights:
    image: redis/redisinsight:latest
    ports:
      - 5540:5540
    profiles:
      - redis
    depends_on:
      - redis
    volumes:
      - redis_insights_data:/data

volumes:
  redis_insights_data:  