FROM alpine:latest AS build
RUN apk update && apk upgrade && apk add git cmake build-base gtest-dev

WORKDIR /app
COPY . .

ARG BUILD_TYPE="Release"
RUN mkdir build && cd build && cmake .. -G"Unix Makefiles" -DCMAKE_BUILD_TYPE=$BUILD_TYPE && cd /app/build && cmake --build .


FROM alpine:latest

RUN apk update && apk upgrade && apk add libstdc++ valgrind valgrind-scripts bash

COPY --from=build /app/build/src/poor-man-s-cache /app/poor-man-s-cache

WORKDIR /callgrind
COPY ./scripts/callgrind.bash ./callgrind.bash

EXPOSE 9001
EXPOSE 9100

RUN addgroup -g 10001 notroot \
    && adduser -u 10001 -G notroot -h /app -s /sbin/nologin -D poor-man-s-cache

USER 10001

ENTRYPOINT  ["/callgrind/callgrind.bash"]