services:
  cache:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - BUILD_TYPE=Release
    extends:
      file: common-compose-config.yaml
      service: cache-common
    profiles:
      - main
    networks:
      - cache_network


  tests-1:
    extends:
      file: common-compose-config.yaml
      service: tests-common
    environment:
      - CACHE_HOST=cache
    profiles:
      - tests
    networks:
      - cache_network

  tests-2:
    extends:
      file: common-compose-config.yaml
      service: tests-common
    environment:
      - CACHE_HOST=cache
    profiles:
      - tests
    networks:
      - cache_network

  tests-3:
    extends:
      file: common-compose-config.yaml
      service: tests-common
    environment:
      - CACHE_HOST=cache
    profiles:
      - tests
    networks:
      - cache_network

  tests-4:
    extends:
      file: common-compose-config.yaml
      service: tests-common
    environment:
      - CACHE_HOST=cache
    profiles:
      - tests
    networks:
      - cache_network

  tests-5:
    extends:
      file: common-compose-config.yaml
      service: tests-common
    environment:
      - CACHE_HOST=cache
    profiles:
      - tests
    networks:
      - cache_network

  tests-6:
    extends:
      file: common-compose-config.yaml
      service: tests-common
    environment:
      - CACHE_HOST=cache
    profiles:
      - tests
    networks:
      - cache_network

  tests-7:
    extends:
      file: common-compose-config.yaml
      service: tests-common
    environment:
      - CACHE_HOST=cache
    profiles:
      - tests
    networks:
      - cache_network

  tests-8:
    extends:
      file: common-compose-config.yaml
      service: tests-common
    environment:
      - CACHE_HOST=cache
    profiles:
      - tests
    networks:
      - cache_network

  tests-9:
    extends:
      file: common-compose-config.yaml
      service: tests-common
    environment:
      - CACHE_HOST=cache
    profiles:
      - tests
    networks:
      - cache_network

  tests-10:
    extends:
      file: common-compose-config.yaml
      service: tests-common
    environment:
      - CACHE_HOST=cache
    profiles:
      - tests
    networks:
      - cache_network

  tests-11:
    extends:
      file: common-compose-config.yaml
      service: tests-common
    environment:
      - CACHE_HOST=cache
    profiles:
      - tests
    networks:
      - cache_network

  tests-12:
    extends:
      file: common-compose-config.yaml
      service: tests-common
    environment:
      - CACHE_HOST=cache
    profiles:
      - tests
    networks:
      - cache_network

  tests-13:
    extends:
      file: common-compose-config.yaml
      service: tests-common
    environment:
      - CACHE_HOST=cache
    profiles:
      - tests
    networks:
      - cache_network

  tests-14:
    extends:
      file: common-compose-config.yaml
      service: tests-common
    environment:
      - CACHE_HOST=cache
    profiles:
      - tests
    networks:
      - cache_network

  tests-15:
    extends:
      file: common-compose-config.yaml
      service: tests-common
    environment:
      - CACHE_HOST=cache
    profiles:
      - tests
    networks:
      - cache_network

  tests-16:
    extends:
      file: common-compose-config.yaml
      service: tests-common
    environment:
      - CACHE_HOST=cache
    profiles:
      - tests
    networks:
      - cache_network

  tests-17:
    extends:
      file: common-compose-config.yaml
      service: tests-common
    environment:
      - CACHE_HOST=cache
    profiles:
      - tests
    networks:
      - cache_network

  tests-18:
    extends:
      file: common-compose-config.yaml
      service: tests-common
    environment:
      - CACHE_HOST=cache
    profiles:
      - tests
    networks:
      - cache_network

  tests-19:
    extends:
      file: common-compose-config.yaml
      service: tests-common
    environment:
      - CACHE_HOST=cache
    profiles:
      - tests
    networks:
      - cache_network

  tests-20:
    extends:
      file: common-compose-config.yaml
      service: tests-common
    environment:
      - CACHE_HOST=cache
    profiles:
      - tests
    networks:
      - cache_network


networks:
  cache_network:
    driver: bridge