apiVersion: v1
kind: Service
metadata:
  name: {{ include "poor-man-s-cache.fullname" . }}
  labels:
    {{- include "poor-man-s-cache.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: server
      protocol: TCP
      name: server
    - port: {{ .Values.service.metricsPort }}
      targetPort: metrics
      protocol: TCP
      name: metrics
  selector:
    {{- include "poor-man-s-cache.selectorLabels" . | nindent 4 }}
