name: Continuous integration
permissions:
  contents: read

on:
  push:
    branches:
    - main
    - dev*
    - release/*
    - codex/*

env:
  DOCKER_IMAGE_NAME: my-image

jobs:
  docker_ci:
    name: Docker CI
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v3
    
    - name: Generate test suite
      run: pip install jinja2 && python generate_compose.py 1

    - name: Build docker images and run unit tests
      run: docker compose --profile main --profile tests build

    - name: Start cache server
      run: docker compose --profile main up --detach

    - name: Run client tests
      run: docker compose --profile client-tests up
      timeout-minutes: 5

    - name: Run load and functional tests
      run: docker compose --profile tests up
      timeout-minutes: 10

    - name: Run load and functional tests (pipelined mode enabled)
      run: docker compose --profile tests-pipelined up
      timeout-minutes: 5

    - name: Run load and functional tests (RESP protocol)
      run: docker compose --profile tests-resp up
      timeout-minutes: 10

    - name: Run load and functional tests (RESP protocol, pipelined mode enabled)
      run: docker compose --profile tests-resp-pipelined up
      timeout-minutes: 5

    - name: Run load and functional tests (request-per-connection clients)
      run: docker compose --profile tests-req-per-conn up
      timeout-minutes: 10

    - name: Stop cache server
      run: docker compose --profile main down
