on:
  push:
    branches:
    - main
    - release/*

env:
  DOCKER_IMAGE_NAME: my-image

jobs:
  docker_ci:
    name: Docker CI
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Docker compose build
      run: docker compose --profile main --profile tests build

    - name: Docker compose up
      run: docker compose --profile main --profile tests up
